version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: db
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - ./forecast-app-db/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env

  auth:
    build:
      context: ./forecast-app-auth
    container_name: auth
    restart: on-failure
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      - HTTP=8080
      - DATABASE_ADDRESS=db:5432
      - DATABASE_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}

  interface:
    build:
      context: ./forecast-app-interface
    container_name: interface
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - auth
    environment:
      - HTTP=8080
      - AUTH-SERVICE-ADDRESS=auth:8081

volumes:
  db-volume:
    external: false