version: "3.8"

services:
  db:
    image: postgres:16.2-alpine
    container_name: db
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - ./forecast-app-db/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env

  auth:
    build:
      context: ./forecast-app-auth
    container_name: auth
    restart: on-failure
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - HTTP=8081
      - DATABASE_ADDRESS=db:5432
      - DATABASE_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}

  predict:
    build:
      context: ./forecast-app-predict
    container_name: predict
    restart: on-failure
    ports:
      - "8082:8082"
    depends_on:
      - db
    environment:
      - HTTP=8082
      - DATABASE_ADDRESS=db:5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - POOL=${POOL}

  interface:
    build:
      context: ./forecast-app-interface
    container_name: interface
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - auth
      - predict
    environment:
      - HTTP=8080
      - AUTH_SERVICE_ADDRESS=auth:8081
      - PREDICT_SERVICE_ADDRESS=predict:8082

volumes:
  db-volume:
    external: false