# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import predict_pb2 as predict__pb2


class PredictServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MakePredict = channel.unary_unary(
                '/PredictService/MakePredict',
                request_serializer=predict__pb2.MakePredictRequest.SerializeToString,
                response_deserializer=predict__pb2.Empty.FromString,
                )
        self.GetPredict = channel.unary_unary(
                '/PredictService/GetPredict',
                request_serializer=predict__pb2.GetPredictRequest.SerializeToString,
                response_deserializer=predict__pb2.GetPredictResponse.FromString,
                )


class PredictServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MakePredict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPredict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PredictServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MakePredict': grpc.unary_unary_rpc_method_handler(
                    servicer.MakePredict,
                    request_deserializer=predict__pb2.MakePredictRequest.FromString,
                    response_serializer=predict__pb2.Empty.SerializeToString,
            ),
            'GetPredict': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPredict,
                    request_deserializer=predict__pb2.GetPredictRequest.FromString,
                    response_serializer=predict__pb2.GetPredictResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PredictService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PredictService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MakePredict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PredictService/MakePredict',
            predict__pb2.MakePredictRequest.SerializeToString,
            predict__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPredict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PredictService/GetPredict',
            predict__pb2.GetPredictRequest.SerializeToString,
            predict__pb2.GetPredictResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
